spring.application.name=product-service2
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/product
spring.datasource.username=postgres
spring.datasource.password=Megha@12.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=XZATcHyCN98RFBScsOU6BuddgZvHWVAlvTcyfNTnxyA=

